name: "Example"
on:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: "Triage"
        uses: rmeissner/safe-pm-action-triage@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          safe-address: ${{ secrets.TARGET_SAFE }}
          snapshot-space: ${{ secrets.SNAPSHOT_SPACE }}