name: "Example"
on:
  issues:
    types: [opened,edited]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: "Triage"
        uses: rmeissner/safe-pm-action-triage@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: '${{ github.event.issues.issue.number }} someprojectstring'
          action: 