name: "Example"
on:
  issues:
    types: [opened,edited]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: "Triage"
        uses: rmeissner/safe-pm-action-triage@main
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          action: 'assign_issue_to_project'
          params: '${{ github.event.issue.number }} 1'